---
# Whenever a tag push matching pattern "v*" then run the job
on:
  push:
    tags:
      - "v*"

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game Job
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        # Ensure that you get the entire project history
        with:
          fetch-depth: 0
      - name: release
        uses: idleberg/create-playdate-release@v0.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: "gray-adventure"
